### ISSUE TITLE
Indentation bug in library function

### ISSUE THREAD

**Issue by ffund** [ca-chow/DesktopPet_Eui#15]
On running `demo.py`:

```
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    from stubby_eui import *
  File "/home/pi/sp21/DesktopPet_Eui/stubby_eui.py", line 41
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by casychow** [comment]
Fixed tab/indentation issues
